### 第一步：模拟登陆，返回token
GET http://localhost:9009/login

### 第二步：请求带上token，请求/user端点
GET http://localhost:9009/user
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInBlcm1zIjpbInVzZXIiXSwidXNlcm5hbWUiOiLlvKDkuIkiLCJpYXQiOjE1NTY1MjU3MDksImV4cCI6MTU1NzczNTMwOX0.l7FtIcCf6uFagoosaX72YpSYPXm5DeDH1cXGUn2JkWknLyc3fLtB_nMD-wHklmdNbIANiidxzhhYb8pbvLVdbQ


### 第三步：请求带上token，请求/admin
GET http://localhost:9009/admin
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInBlcm1zIjpbInVzZXIiXSwidXNlcm5hbWUiOiLlvKDkuIkiLCJpYXQiOjE1NTY1MjU3MDksImV4cCI6MTU1NzczNTMwOX0.l7FtIcCf6uFagoosaX72YpSYPXm5DeDH1cXGUn2JkWknLyc3fLtB_nMD-wHklmdNbIANiidxzhhYb8pbvLVdbQ

### 国际化
GET http://localhost:9009/i18n?locale=zh_CN


